ScarletDawnAirbases = {}
ScarletDawnAirbases[1] = {}
ScarletDawnAirbases[1]["Airbase"] = "Abu al-Duhur"
ScarletDawnAirbases[1]["Coalition"] = 1
ScarletDawnAirbases[2] = {}
ScarletDawnAirbases[2]["Airbase"] = "Adana Sakirpasa"
ScarletDawnAirbases[2]["Coalition"] = 2
ScarletDawnAirbases[3] = {}
ScarletDawnAirbases[3]["Airbase"] = "Aleppo"
ScarletDawnAirbases[3]["Coalition"] = 1
ScarletDawnAirbases[4] = {}
ScarletDawnAirbases[4]["Airbase"] = "Al-Dumayr"
ScarletDawnAirbases[4]["Coalition"] = 1
ScarletDawnAirbases[5] = {}
ScarletDawnAirbases[5]["Airbase"] = "Al Qusayr"
ScarletDawnAirbases[5]["Coalition"] = 1
ScarletDawnAirbases[6] = {}
ScarletDawnAirbases[6]["Airbase"] = "An Nasiriyah"
ScarletDawnAirbases[6]["Coalition"] = 1
ScarletDawnAirbases[7] = {}
ScarletDawnAirbases[7]["Airbase"] = "Bassel Al-Assad"
ScarletDawnAirbases[7]["Coalition"] = 1
ScarletDawnAirbases[8] = {}
ScarletDawnAirbases[8]["Airbase"] = "Beirut-Rafic Hariri"
ScarletDawnAirbases[8]["Coalition"] = 1
ScarletDawnAirbases[9] = {}
ScarletDawnAirbases[9]["Airbase"] = "Damascus"
ScarletDawnAirbases[9]["Coalition"] = 1
ScarletDawnAirbases[10] = {}
ScarletDawnAirbases[10]["Airbase"] = "Eyn Shemer"
ScarletDawnAirbases[10]["Coalition"] = 1
ScarletDawnAirbases[11] = {}
ScarletDawnAirbases[11]["Airbase"] = "Haifa"
ScarletDawnAirbases[11]["Coalition"] = 2
ScarletDawnAirbases[12] = {}
ScarletDawnAirbases[12]["Airbase"] = "Hama"
ScarletDawnAirbases[12]["Coalition"] = 1
ScarletDawnAirbases[13] = {}
ScarletDawnAirbases[13]["Airbase"] = "Hatay"
ScarletDawnAirbases[13]["Coalition"] = 1
ScarletDawnAirbases[14] = {}
ScarletDawnAirbases[14]["Airbase"] = "Jirah"
ScarletDawnAirbases[14]["Coalition"] = 1
ScarletDawnAirbases[15] = {}
ScarletDawnAirbases[15]["Airbase"] = "King Hussein Air College"
ScarletDawnAirbases[15]["Coalition"] = 1
ScarletDawnAirbases[16] = {}
ScarletDawnAirbases[16]["Airbase"] = "Kiryat Shmona"
ScarletDawnAirbases[16]["Coalition"] = 1
ScarletDawnAirbases[17] = {}
ScarletDawnAirbases[17]["Airbase"] = "Khalkhalah"
ScarletDawnAirbases[17]["Coalition"] = 1
ScarletDawnAirbases[18] = {}
ScarletDawnAirbases[18]["Airbase"] = "Kuweires"
ScarletDawnAirbases[18]["Coalition"] = 1
ScarletDawnAirbases[19] = {}
ScarletDawnAirbases[19]["Airbase"] = "Marj as Sultan North"
ScarletDawnAirbases[19]["Coalition"] = 1
ScarletDawnAirbases[20] = {}
ScarletDawnAirbases[20]["Airbase"] = "Marj as Sultan South"
ScarletDawnAirbases[20]["Coalition"] = 1
ScarletDawnAirbases[21] = {}
ScarletDawnAirbases[21]["Airbase"] = "Marj Ruhayyil"
ScarletDawnAirbases[21]["Coalition"] = 1
ScarletDawnAirbases[22] = {}
ScarletDawnAirbases[22]["Airbase"] = "Megiddo"
ScarletDawnAirbases[22]["Coalition"] = 1
ScarletDawnAirbases[23] = {}
ScarletDawnAirbases[23]["Airbase"] = "Mezzeh"
ScarletDawnAirbases[23]["Coalition"] = 1
ScarletDawnAirbases[24] = {}
ScarletDawnAirbases[24]["Airbase"] = "Minakh"
ScarletDawnAirbases[24]["Coalition"] = 1
ScarletDawnAirbases[25] = {}
ScarletDawnAirbases[25]["Airbase"] = "Qabr as Sitt"
ScarletDawnAirbases[25]["Coalition"] = 1
ScarletDawnAirbases[26] = {}
ScarletDawnAirbases[26]["Airbase"] = "Rayak"
ScarletDawnAirbases[26]["Coalition"] = 1
ScarletDawnAirbases[27] = {}
ScarletDawnAirbases[27]["Airbase"] = "Rene Mouawad"
ScarletDawnAirbases[27]["Coalition"] = 1
ScarletDawnAirbases[28] = {}
ScarletDawnAirbases[28]["Airbase"] = "Taftanaz"
ScarletDawnAirbases[28]["Coalition"] = 1
ScarletDawnAirbases[29] = {}
ScarletDawnAirbases[29]["Airbase"] = "Wujah Al Hajar"
ScarletDawnAirbases[29]["Coalition"] = 1
