BlackpoolAirbases = {}
BlackpoolAirbases[1] = {}
BlackpoolAirbases[1]["Airbase"] = "Abu al-Duhur"
BlackpoolAirbases[1]["Coalition"] = 1
BlackpoolAirbases[2] = {}
BlackpoolAirbases[2]["Airbase"] = "Adana Sakirpasa"
BlackpoolAirbases[2]["Coalition"] = 2
BlackpoolAirbases[3] = {}
BlackpoolAirbases[3]["Airbase"] = "Aleppo"
BlackpoolAirbases[3]["Coalition"] = 1
BlackpoolAirbases[4] = {}
BlackpoolAirbases[4]["Airbase"] = "Al-Dumayr"
BlackpoolAirbases[4]["Coalition"] = 1
BlackpoolAirbases[5] = {}
BlackpoolAirbases[5]["Airbase"] = "Al Qusayr"
BlackpoolAirbases[5]["Coalition"] = 1
BlackpoolAirbases[6] = {}
BlackpoolAirbases[6]["Airbase"] = "An Nasiriyah"
BlackpoolAirbases[6]["Coalition"] = 1
BlackpoolAirbases[7] = {}
BlackpoolAirbases[7]["Airbase"] = "Bassel Al-Assad"
BlackpoolAirbases[7]["Coalition"] = 1
BlackpoolAirbases[8] = {}
BlackpoolAirbases[8]["Airbase"] = "Beirut-Rafic Hariri"
BlackpoolAirbases[8]["Coalition"] = 1
BlackpoolAirbases[9] = {}
BlackpoolAirbases[9]["Airbase"] = "Damascus"
BlackpoolAirbases[9]["Coalition"] = 1
BlackpoolAirbases[10] = {}
BlackpoolAirbases[10]["Airbase"] = "Eyn Shemer"
BlackpoolAirbases[10]["Coalition"] = 1
BlackpoolAirbases[11] = {}
BlackpoolAirbases[11]["Airbase"] = "Haifa"
BlackpoolAirbases[11]["Coalition"] = 2
BlackpoolAirbases[12] = {}
BlackpoolAirbases[12]["Airbase"] = "Hama"
BlackpoolAirbases[12]["Coalition"] = 1
BlackpoolAirbases[13] = {}
BlackpoolAirbases[13]["Airbase"] = "Hatay"
BlackpoolAirbases[13]["Coalition"] = 1
BlackpoolAirbases[14] = {}
BlackpoolAirbases[14]["Airbase"] = "Jirah"
BlackpoolAirbases[14]["Coalition"] = 1
BlackpoolAirbases[15] = {}
BlackpoolAirbases[15]["Airbase"] = "King Hussein Air College"
BlackpoolAirbases[15]["Coalition"] = 1
BlackpoolAirbases[16] = {}
BlackpoolAirbases[16]["Airbase"] = "Kiryat Shmona"
BlackpoolAirbases[16]["Coalition"] = 1
BlackpoolAirbases[17] = {}
BlackpoolAirbases[17]["Airbase"] = "Khalkhalah"
BlackpoolAirbases[17]["Coalition"] = 1
BlackpoolAirbases[18] = {}
BlackpoolAirbases[18]["Airbase"] = "Kuweires"
BlackpoolAirbases[18]["Coalition"] = 1
BlackpoolAirbases[19] = {}
BlackpoolAirbases[19]["Airbase"] = "Marj as Sultan North"
BlackpoolAirbases[19]["Coalition"] = 1
BlackpoolAirbases[20] = {}
BlackpoolAirbases[20]["Airbase"] = "Marj as Sultan South"
BlackpoolAirbases[20]["Coalition"] = 1
BlackpoolAirbases[21] = {}
BlackpoolAirbases[21]["Airbase"] = "Marj Ruhayyil"
BlackpoolAirbases[21]["Coalition"] = 1
BlackpoolAirbases[22] = {}
BlackpoolAirbases[22]["Airbase"] = "Megiddo"
BlackpoolAirbases[22]["Coalition"] = 1
BlackpoolAirbases[23] = {}
BlackpoolAirbases[23]["Airbase"] = "Mezzeh"
BlackpoolAirbases[23]["Coalition"] = 1
BlackpoolAirbases[24] = {}
BlackpoolAirbases[24]["Airbase"] = "Minakh"
BlackpoolAirbases[24]["Coalition"] = 1
BlackpoolAirbases[25] = {}
BlackpoolAirbases[25]["Airbase"] = "Qabr as Sitt"
BlackpoolAirbases[25]["Coalition"] = 1
BlackpoolAirbases[26] = {}
BlackpoolAirbases[26]["Airbase"] = "Rayak"
BlackpoolAirbases[26]["Coalition"] = 1
BlackpoolAirbases[27] = {}
BlackpoolAirbases[27]["Airbase"] = "Rene Mouawad"
BlackpoolAirbases[27]["Coalition"] = 1
BlackpoolAirbases[28] = {}
BlackpoolAirbases[28]["Airbase"] = "Taftanaz"
BlackpoolAirbases[28]["Coalition"] = 1
BlackpoolAirbases[29] = {}
BlackpoolAirbases[29]["Airbase"] = "Wujah Al Hajar"
BlackpoolAirbases[29]["Coalition"] = 1
